""" Agent Extension Interfaces go here
AEIs mediate interaction between generative
natural language models and APIs, programming interfaces, etc."""

from __future__ import print_function

import os.path

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from email.message import EmailMessage
import google.auth

import mimetypes

from email.mime.audio import MIMEAudio
from email.mime.base import MIMEBase
from email.mime.image import MIMEImage
from email.mime.text import MIMEText

import base64

email_from = 'SENDER'
my_email = 'YOUR_GMAIL'

# If modifying these scopes, delete the file token.json.
SCOPES = ['https://www.googleapis.com/auth/gmail.modify', 'https://www.googleapis.com/auth/calendar.events']

# lists of AEI commands the agent can call, and arguments it can pass
aeiCommands = {'/;SENDMAIL;/':None, '/;GOOGSEARCH;/':None, '/;CALENDAR;/':{'/;VIEW;/':''}}

def sendMail(recipient, subject, content):
    """Create and send an email message
    Print the returned  message id
    Returns: Message object, including message id

    Load pre-authorized user credentials from the environment.
    TODO(developer) - See https://developers.google.com/identity
    for guides on implementing OAuth2 for the application.
    """
    creds=None
    if os.path.exists('token.json'):
        creds = Credentials.from_authorized_user_file('token.json', SCOPES)
    # If there are no (valid) credentials available, let the user log in.
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(
                'credentials.json', SCOPES)
            creds = flow.run_local_server(port=0)
        # Save the credentials for the next run
        with open('token.json', 'w') as token:
            token.write(creds.to_json())

    try:
        service = build('gmail', 'v1', credentials=creds)
        message = EmailMessage()

        message.set_content(content)

        message['To'] = recipient
        message['From'] = email_from
        message['Subject'] = subject

        # encoded message
        encoded_message = base64.urlsafe_b64encode(message.as_bytes()) \
            .decode()

        create_message = {
            'raw': encoded_message
        }
        # pylint: disable=E1101
        send_message = (service.users().messages().send(userId="me", body=create_message).execute())
        print(F'Message Id: {send_message["id"]}')
    except HttpError as error:
        print(F'An error occurred: {error}')
        send_message = None
    return send_message


def loadInbox(): #incomplete function
    """Display threads with long conversations(>= 3 messages)
    Return: None

    Load pre-authorized user credentials from the environment.
    TODO(developer) - See https://developers.google.com/identity
    for guides on implementing OAuth2 for the application.
    """
    creds=None
    if os.path.exists('token.json'):
        creds = Credentials.from_authorized_user_file('token.json', SCOPES)
    # If there are no (valid) credentials available, let the user log in.
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(
                'credentials.json', SCOPES)
            creds = flow.run_local_server(port=0)
        # Save the credentials for the next run
        with open('token.json', 'w') as token:
            token.write(creds.to_json())

    try:
        # create gmail api client
        service = build('gmail', 'v1', credentials=creds)

        # pylint: disable=maybe-no-member
        # pylint: disable:R1710
        threads = service.users().threads().list(userId='me').execute().get('threads', [])
        for thread in threads:
            tdata = service.users().threads().get(userId='me', id=thread['id']).execute()
            nmsgs = len(tdata['messages'])

            # skip if <3 msgs in thread
            if nmsgs == 1:
                msg = tdata['messages'][0]['payload']
                subject = ''
                for header in msg['headers']:
                    if header['name'] == 'Subject':
                        subject = header['value']
                        break
                if subject:  # skip if no Subject line
                    print(F'- {subject}, {nmsgs}')
        return threads

    except HttpError as error:
        print(F'An error occurred: {error}')


def calendar(action, start, end=None, maxResults=10, loc=None, name='Autogenerated Event', desc='This even was autogenerated by AI.', eventId=None):
    """Shows basic usage of the Google Calendar API.
    Prints the start and name of the next 10 events on the user's calendar.
    """
    action = str(action).lower()

    creds = None
    # The file token.json stores the user's access and refresh tokens, and is
    # created automatically when the authorization flow completes for the first
    # time.
    if os.path.exists('token.json'):
        creds = Credentials.from_authorized_user_file('token.json', SCOPES)
    # If there are no (valid) credentials available, let the user log in.
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(
                'credentials.json', SCOPES)
            creds = flow.run_local_server(port=0)
        # Save the credentials for the next run
        with open('token.json', 'w') as token:
            token.write(creds.to_json())

    try:
        service = build('calendar', 'v3', credentials=creds)

        # Call the Calendar API
        if action == 'view':

            #print('Getting the upcoming 10 events')
            events_result = service.events().list(calendarId='primary', timeMin=start, timeMax=end,
                                                  maxResults=maxResults, singleEvents=True,
                                                  orderBy='startTime').execute()
            #print(events_result)
            events = events_result.get('items', [])

            if not events:
                #print('No upcoming events found.')
                return 'You have successfully checked the calendar. There are no matching events.'

            eventsText = ''
            for event in events:
                eventStart = event['start'].get('dateTime', event['start'].get('date'))
                eventSummary = event['summary']
                eventId = event['id']
                if eventsText:
                    eventsText+='\n'
                eventsText+=eventSummary+'\n'+'Start: '+eventStart+'\n'+'eventId: '+eventId
                

            returnPrompt = 'You have successfully checked the calendar. Matching events:\n'
            return returnPrompt + eventsText

        elif action == 'delete':
            try:
                event = service.events().get(calendarId='primary', eventId=eventId).execute()
                eventName = event['summary']
                eventId = event['id']

                if input(f'\nEnter "y" to delete event "{eventName}". Any other string to abort.'):
                    service.events().delete(calendarId='primary', eventId=eventId).execute()
                    return f'You deleted the event "{eventName}".'
                else:
                    return 'User aborted the deletion.'
            except Exception as e:
                print(f'An error occurred: {e}')
                return f'An error occurred: {e}'

        elif action == 'create':
            event = {
                'summary': name,
                'location': loc,
                'description': desc,
                'start': {
                    'dateTime': start,
                    'timeZone': 'America/Los_Angeles',
                },
                'end': {
                    'dateTime': end,
                    'timeZone': 'America/Los_Angeles',
                },
                'attendees': [
                    {'email': my_email},
                ],
                'reminders': {
                    'useDefault': False,
                    'overrides': [
                        {'method': 'email', 'minutes': 3 * 60},
                        {'method': 'popup', 'minutes': 60},
                    ],
                },
            }

            event = service.events().insert(calendarId='primary', body=event).execute()
            print ('Event created by Assistant: %s' % (event.get('htmlLink')))
            return 'You have successfully created the event.'




    except HttpError as error:
        print('An error occurred: %s' % error)


def wtxt(text, fid):
    """/;WTEXT;/<Text to write>/;PATH;/<Path to write to>"""
    try:
        with open('./'+fid+'.txt', 'w') as f:
            f.write(text)
        print(f'\nText written to {fid}.txt.')
        return 'You successfully wrote the text file.'
    except:
        print('\nAn error occurred in writing the text file.')
        return 'An error occurred in writing the text file.'

def rtxt(fid):
    try:
        with open('./'+fid+'.txt', 'r') as f:
            text = f.read()
        print(f'\nAssistant read {fid}.txt.')
        return 'You successfully read the text file. Its content is as follows:\n\n'+text
    except:
        print(f'\nAn error occurred in reading {fid}.txt.')
        return 'An error occurred in reading the text file.'